---
title: "Phase II, single arm bernoulli outcomes"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA, message=FALSE, warning=FALSE, fig.width = 8, fig.height = 8, fig.align='center', eval=TRUE)
```

```{r, cache=FALSE, echo=FALSE, results='hide'}
library(SeqSGPV)
nreps <- 20
# files.sources <- list.files("../../R/",pattern = ".R")
# sapply(paste0("R/",files.sources),source)
# library(epiR)
```

## Example 4: Re-visiting example 1 with prior-based effect generation

This example uses a small number of replicates to demonstrate how to
obtain end of study replicates where the effect generation follows a
random distribution. For each replicate, a success probability is drawn
uniformly between 0.1 and 0.5.

```{r, cache=TRUE, fig.height=6, fig.width=6, eval=TRUE}
system.time(PRISM1c <-  SeqSGPV(nreps            = nreps,
                               dataGeneration   = rbinom, dataGenArgs = list(n=40, size=1, prob = .2),
                               effectGeneration = runif, effectGenArgs=list(n=1, min=-.1, max = .3),  effectScale  = "identity",
                               allocation       = 1,
                               effectPN         = 0.2,
                               null             = "less",
                               PRISM            = list(deltaL2 = NA, deltaL1 = NA, 
                                                       deltaG1 = .225, deltaG2 = .4),
                               modelFit         = binomCI,
                               modelFitArgs     = list(conf.level=.95, 
                                                       prior.shape1=0.005, prior.shape2=0.005,
                                                       methods="bayes", type="central"),
                               wait             = 5:10,
                               steps            = 1:3,
                               affirm           = 0:1,
                               lag              = c(0,5,10),
                               N                = 35:40,
                               printProgress    = FALSE))
```

```{r, eval=TRUE}
 head(PRISM1c$mcmcEOS$W5_S1_A0_L0_N35)
```
